name: Sunday
options:
  bundleIdPrefix: it.sunday
  deploymentTarget:
    iOS: 17.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: it.sunday.app
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: "L3N5LHJD5Y"
targets:
  Sunday:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources/Assets.xcassets
      - Resources/LaunchScreen.storyboard
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: Sun Day
        LSApplicationCategoryType: public.app-category.healthcare-fitness
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations: 
          - UIInterfaceOrientationPortrait
        UIRequiresFullScreen: true
        NSLocationWhenInUseUsageDescription: "Sun Day needs your location to determine UV levels at your current position"
        NSLocationAlwaysAndWhenInUseUsageDescription: "Sun Day needs your location to track UV exposure throughout the day"
        NSHealthShareUsageDescription: "Sun Day reads your health data to provide personalized vitamin D recommendations"
        NSHealthUpdateUsageDescription: "Sun Day saves your vitamin D intake data to Health app"
        UIUserInterfaceStyle: Light
        NSUserNotificationCenterUsageDescription: "Sun Day sends reminders when the sun rises and sets to help you track vitamin D"
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_ASSET_PATHS: "Sources"
        CODE_SIGN_ENTITLEMENTS: Resources/Sunday.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
    capabilities:
      - com.apple.HealthKit
      - com.apple.BackgroundModes:
          enabled: true
          modes:
            - location
